### ISSUE TITLE
Errors when copy same files two times (CIFS)

### ISSUE THREAD

**Issue by mayasd** [keensoft/alfresco-myfiles-quota#9]
Hi,

- Mounting share with CIFS (Linux).
- Copy file (PDF, OpenDocument...).
- When file upload is done, copy same file again.
- My file explorer crash and sometimes file is read-only...in this case, restart of Alfresco is necessary.

extension version : 2.0.3
alfresco version : 5.0.d

**Logs :**

```
2016-02-25 15:28:49,178 ERROR [org.alfresco.fileserver] [AlfJLANWorker16] Error from JLAN
org.alfresco.error.AlfrescoRuntimeException: 01250012 Failed to execute transaction-level behaviour public abstract void org.alfresco.repo.content.ContentServi
cePolicies$OnContentPropertyUpdatePolicy.onContentPropertyUpdate(org.alfresco.service.cmr.repository.NodeRef,org.alfresco.service.namespace.QName,org.alfresco.
service.cmr.repository.ContentData,org.alfresco.service.cmr.repository.ContentData) in transaction f9cc7451-083e-49d8-bec0-a1cd4626c7a6
        at org.alfresco.repo.policy.TransactionBehaviourQueue.execute(TransactionBehaviourQueue.java:257)
        at org.alfresco.repo.policy.TransactionBehaviourQueue.beforeCommit(TransactionBehaviourQueue.java:134)
        at org.alfresco.util.transaction.TransactionSupportUtil$TransactionSynchronizationImpl.doBeforeCommit(TransactionSupportUtil.java:535)
        at org.alfresco.util.transaction.TransactionSupportUtil$TransactionSynchronizationImpl.doBeforeCommit(TransactionSupportUtil.java:514)
        at org.alfresco.util.transaction.TransactionSupportUtil$TransactionSynchronizationImpl.beforeCommit(TransactionSupportUtil.java:479)
        at org.springframework.transaction.support.TransactionSynchronizationUtils.triggerBeforeCommit(TransactionSynchronizationUtils.java:95)
        at org.springframework.transaction.support.AbstractPlatformTransactionManager.triggerBeforeCommit(AbstractPlatformTransactionManager.java:925)
        at org.springframework.transaction.support.AbstractPlatformTransactionManager.processCommit(AbstractPlatformTransactionManager.java:738)
        at org.springframework.transaction.support.AbstractPlatformTransactionManager.commit(AbstractPlatformTransactionManager.java:724)
        at org.springframework.transaction.interceptor.TransactionAspectSupport.commitTransactionAfterReturning(TransactionAspectSupport.java:475)
        at org.alfresco.util.transaction.SpringAwareUserTransaction.commit(SpringAwareUserTransaction.java:482)
        at org.alfresco.repo.transaction.RetryingTransactionHelper.doInTransaction(RetryingTransactionHelper.java:479)
        at org.alfresco.repo.transaction.RetryingTransactionHelper.doInTransaction(RetryingTransactionHelper.java:345)
        at org.alfresco.filesys.repo.CommandExecutorImpl.execute(CommandExecutorImpl.java:102)
        at org.alfresco.filesys.repo.NonTransactionalRuleContentDiskDriver.renameFile(NonTransactionalRuleContentDiskDriver.java:487)
        at org.alfresco.filesys.repo.LegacyFileStateDriver.renameFile(LegacyFileStateDriver.java:622)
        at org.alfresco.filesys.repo.BufferedContentDiskDriver.renameFile(BufferedContentDiskDriver.java:521)
        at org.alfresco.jlan.smb.server.NTProtocolHandler.procRenameFile(NTProtocolHandler.java:2928)
        at org.alfresco.jlan.smb.server.NTProtocolHandler.runProtocol(NTProtocolHandler.java:279)
        at org.alfresco.jlan.smb.server.SMBSrvSession.runHandler(SMBSrvSession.java:1396)
        at org.alfresco.jlan.smb.server.SMBSrvSession.processPacket(SMBSrvSession.java:1490)
        at org.alfresco.jlan.smb.server.nio.NIOCIFSThreadRequest.runRequest(NIOCIFSThreadRequest.java:150)
        at org.alfresco.jlan.server.thread.ThreadRequestPool$ThreadWorker.run(ThreadRequestPool.java:153)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
        at org.alfresco.extension.folderquota.behaviour.FolderQuotaBehaviour.onContentPropertyUpdate(FolderQuotaBehaviour.java:105)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:483)
        at org.alfresco.repo.policy.JavaBehaviour$JavaMethodInvocationHandler.invoke(JavaBehaviour.java:174)
        at com.sun.proxy.$Proxy140.onContentPropertyUpdate(Unknown Source)
        at sun.reflect.GeneratedMethodAccessor582.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:483)
        at org.alfresco.repo.policy.TransactionBehaviourQueue.execute(TransactionBehaviourQueue.java:245)
        ... 23 more
```

**Comment by angelborroy-ks** [comment]
It seems more related with old JLAN implementation than with the module. Nevertheless, a 2.0.4 patch has been released to solve this. Please, provide some feedback: we can not reproduce this issue.

**Comment by mayasd** [comment]
Wow ! Thanks for your patch. But the error always seems present but not in the same line (line 109 now) :

```
2016-02-26 09:32:10,412  ERROR [org.alfresco.fileserver] [AlfJLANWorker1] Error from JLAN
org.alfresco.error.AlfrescoRuntimeException: 01260015 Failed to execute transaction-level behaviour public abstract void org.alfresco.repo.content.ContentServicePolicies$OnContentPropertyUpdatePolicy.onContentPropertyUpdate(org.alfresco.service.cmr.repository.NodeRef,org.alfresco.service.namespace.QName,org.alfresco.service.cmr.repository.ContentData,org.alfresco.service.cmr.repository.ContentData) in transaction a6ee5055-ee95-4c0f-a9c6-7715624fa78b
        at org.alfresco.repo.policy.TransactionBehaviourQueue.execute(TransactionBehaviourQueue.java:257)
        at org.alfresco.repo.policy.TransactionBehaviourQueue.beforeCommit(TransactionBehaviourQueue.java:134)
        at org.alfresco.util.transaction.TransactionSupportUtil$TransactionSynchronizationImpl.doBeforeCommit(TransactionSupportUtil.java:535)
        at org.alfresco.util.transaction.TransactionSupportUtil$TransactionSynchronizationImpl.doBeforeCommit(TransactionSupportUtil.java:514)
        at org.alfresco.util.transaction.TransactionSupportUtil$TransactionSynchronizationImpl.beforeCommit(TransactionSupportUtil.java:479)
        at org.springframework.transaction.support.TransactionSynchronizationUtils.triggerBeforeCommit(TransactionSynchronizationUtils.java:95)
        at org.springframework.transaction.support.AbstractPlatformTransactionManager.triggerBeforeCommit(AbstractPlatformTransactionManager.java:925)
        at org.springframework.transaction.support.AbstractPlatformTransactionManager.processCommit(AbstractPlatformTransactionManager.java:738)
        at org.springframework.transaction.support.AbstractPlatformTransactionManager.commit(AbstractPlatformTransactionManager.java:724)
        at org.springframework.transaction.interceptor.TransactionAspectSupport.commitTransactionAfterReturning(TransactionAspectSupport.java:475)
        at org.alfresco.util.transaction.SpringAwareUserTransaction.commit(SpringAwareUserTransaction.java:482)
        at org.alfresco.repo.transaction.RetryingTransactionHelper.doInTransaction(RetryingTransactionHelper.java:479)
        at org.alfresco.repo.transaction.RetryingTransactionHelper.doInTransaction(RetryingTransactionHelper.java:345)
        at org.alfresco.filesys.repo.CommandExecutorImpl.execute(CommandExecutorImpl.java:102)
        at org.alfresco.filesys.repo.NonTransactionalRuleContentDiskDriver.renameFile(NonTransactionalRuleContentDiskDriver.java:487)
        at org.alfresco.filesys.repo.LegacyFileStateDriver.renameFile(LegacyFileStateDriver.java:622)
        at org.alfresco.filesys.repo.BufferedContentDiskDriver.renameFile(BufferedContentDiskDriver.java:521)
        at org.alfresco.jlan.smb.server.NTProtocolHandler.procRenameFile(NTProtocolHandler.java:2928)
        at org.alfresco.jlan.smb.server.NTProtocolHandler.runProtocol(NTProtocolHandler.java:279)
        at org.alfresco.jlan.smb.server.SMBSrvSession.runHandler(SMBSrvSession.java:1396)
        at org.alfresco.jlan.smb.server.SMBSrvSession.processPacket(SMBSrvSession.java:1490)
        at org.alfresco.jlan.smb.server.nio.NIOCIFSThreadRequest.runRequest(NIOCIFSThreadRequest.java:150)
        at org.alfresco.jlan.server.thread.ThreadRequestPool$ThreadWorker.run(ThreadRequestPool.java:153)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
        at org.alfresco.extension.folderquota.behaviour.FolderQuotaBehaviour.onContentPropertyUpdate(FolderQuotaBehaviour.java:109)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:483)
        at org.alfresco.repo.policy.JavaBehaviour$JavaMethodInvocationHandler.invoke(JavaBehaviour.java:174)
        at com.sun.proxy.$Proxy134.onContentPropertyUpdate(Unknown Source)
        at sun.reflect.GeneratedMethodAccessor674.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:483)
        at org.alfresco.repo.policy.TransactionBehaviourQueue.execute(TransactionBehaviourQueue.java:245)
        ... 23 more
```

**Comment by angelborroy-ks** [comment]
We've package a new patch. Please, download again 2.0.4 and come back to tell how it's going.

**Comment by mayasd** [comment]
There are not errors anymore. Thank you !
